- name: Nexus
  hosts: all
  become: yes
  vars_prompt:
   - name: admin_password
     prompt: "Admin password"
     private: yes
   - name: user_password
     prompt: "User_password"
     private: yes

  vars:
    nexus_admin_password: "{{ admin_password }}"
    nexus_docker_hosted_port: 8182
    nexus_docker_proxy_port: 8181
    nexus_docker_group_port: 8183
    nexus_anonymous_access: true
    nexus_docker_bearer_token_realm: true
    nexus_npm_bearer_token_realm: true
    nexus_config_maven: true
    nexus_config_pypi: true
    nexus_config_docker: true
    nexus_config_npm: true
    nexus_config_apt: true
    nexus_config_helm: true
    nexus_config_conda: true
    nexus_roles:
      - id: docker-contributor  # can map to a LDAP group id, also used as a key to update a role
        name: docker-contributor
        description: docker-contributor
        privileges:
          - nx-repository-admin-docker-docker-group-*
          - nx-repository-admin-docker-docker-hosted-*
          - nx-repository-view-docker-docker-group-*
          - nx-repository-view-docker-docker-hosted-*
        roles: []
      - id: helm-contributor  # can map to a LDAP group id, also used as a key to update a role
        name: helm-contributor
        description: helm-contributor
        privileges:
          - nx-repository-admin-helm-helm-hosted-*
          - nx-repository-view-helm-*-*
        roles: []
      - id: npm-contributor  # can map to a LDAP group id, also used as a key to update a role
        name: npm-contributor
        description: npm-contributor
        privileges:
          - nx-repository-admin-npm-npm-hosted-*
          - nx-repository-admin-npm-npm-group-*
          - nx-repository-view-npm-*-*
        roles: []
    nexus_local_users:
      - username: docker-contributor
        first_name: Docker
        last_name: Contributor
        email: docker-contributor@company.com
        password: "{{ user_password }}"
        roles:
          - docker-contributor
      - username: helm-contributor
        first_name: Helm
        last_name: Contributor
        email: helm-contributor@company.com
        password: "{{ user_password }}"
        roles:
          - helm-contributor
      - username: npm-contributor
        first_name: npm
        last_name: Contributor
        email: npm-contributor@company.com
        password: "{{ user_password }}"
        roles:
          - npm-contributor
    nexus_repos_cleanup_policies:
      - name: mvn_cleanup
        format: maven2
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: conda_cleanup
        format: conda
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: apt_cleanup
        format: apt
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: docker_cleanup
        format: docker
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: helm_cleanup
        format: helm
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: npm_cleanup
        format: npm
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
      - name: pypi_cleanup
        format: pypi
        mode:
        notes: ""
        criteria:
          lastDownloaded: 15
    nexus_repos_maven_proxy: []
    nexus_repos_maven_hosted: []
    nexus_repos_maven_group: []
    nexus_scheduled_tasks:
      - name: compact-default-blobstore
        cron: '0 0 22 * * ?'
        typeId: blobstore.compact
        task_alert_email: alerts@example.org
        taskProperties:
          blobstoreName: "default"
      - name: Purge unused docker manifests and images
        cron: '0 55 23 * * ?'
        typeId: "repository.docker.gc"
        taskProperties:
          repositoryName: "*"
      - name: Purge incomplete docker uploads
        cron: '0 0 0 * * ?'
        typeId: "repository.docker.upload-purge"
        taskProperties:
          age: "24"
    nexus_repos_pypi_hosted:
      - name: pypi-hosted
        version_policy: release
        write_policy: allow  # one of "allow", "allow_once" or "deny"
    nexus_repos_pypi_group:
      - name: pypi-all
        member_repos:
          - pypi-hosted
          - pypi.org
    nexus_repos_pypi_proxy:
      - name: pypi.org
        remote_url: 'https://pypi.org/'
    _nexus_repos_docker_defaults:
      blob_store: "{{ nexus_blob_names.docker.blob }}"
      force_basic_auth: false
      strict_content_validation: true
      version_policy: release  # release, snapshot or mixed
      layout_policy: strict  # strict or permissive
      write_policy: allow_once  # one of "allow", "allow_once" or "deny"
      maximum_component_age: 1440  # Nexus gui default. For proxies only
      maximum_metadata_age: 1440  # Nexus gui default. For proxies only
      negative_cache_enabled: true  # Nexus gui default. For proxies only
      negative_cache_ttl: 1440  # Nexus gui default. For proxies only
      cache_foreign_layers: false  # Nexus gui default. For proxies only
      foreign_layer_url_whitelist: []  # Nexus gui default. For proxies only
    nexus_repos_docker_hosted:
      - name: docker-hosted
        http_port: "{{ nexus_docker_hosted_port }}"
        v1_enabled: False
    nexus_repos_docker_proxy:
      - name: registry-1.docker.io
        http_port: "{{ nexus_docker_proxy_port }}"
        v1_enabled: False
        index_type: "HUB"
        remote_url: "https://registry-1.docker.io"
        use_nexus_certificates_to_access_index: false
        # cache_foreign_layers: true
        # foreign_layer_url_whitelist:
        #   - "https?://go\\.microsoft\\.com/.*"
        #   - "https://.*\\.azurecr\\.io/.*"
        # maximum_component_age: 1440
        # maximum_metadata_age: 1440
        # negative_cache_enabled: true
        # negative_cache_ttl: 1440
      - name: quay.io
        v1_enabled: False
        index_type: "REGISTRY"
        remote_url: "https://quay.io"
        use_nexus_certificates_to_access_index: false
        # cache_foreign_layers: true
        # foreign_layer_url_whitelist:
        #   - "https?://go\\.microsoft\\.com/.*"
        #   - "https://.*\\.azurecr\\.io/.*"
        # maximum_component_age: 1440
        # maximum_metadata_age: 1440
        # negative_cache_enabled: true
        # negative_cache_ttl: 1440
      - name: gcr.io
        v1_enabled: False
        index_type: "REGISTRY"
        remote_url: "https://gcr.io"
        use_nexus_certificates_to_access_index: false
        # cache_foreign_layers: true
        # foreign_layer_url_whitelist:
        #   - "https?://go\\.microsoft\\.com/.*"
        #   - "https://.*\\.azurecr\\.io/.*"
        # maximum_component_age: 1440
        # maximum_metadata_age: 1440
        # negative_cache_enabled: true
        # negative_cache_ttl: 1440
      - name: ghcr.io
        v1_enabled: False
        index_type: "REGISTRY"
        remote_url: "https://ghcr.io"
        use_nexus_certificates_to_access_index: false
        # cache_foreign_layers: true
        # foreign_layer_url_whitelist:
        #   - "https?://go\\.microsoft\\.com/.*"
        #   - "https://.*\\.azurecr\\.io/.*"
        # maximum_component_age: 1440
        # maximum_metadata_age: 1440
        # negative_cache_enabled: true
        # negative_cache_ttl: 1440
    nexus_repos_docker_group:
      - name: docker-group
        http_port: "{{ nexus_docker_group_port }}"
        v1_enabled: True
        member_repos:
          - docker-hosted
          - registry-1.docker.io
          - quay.io
          - gcr.io
          - ghcr.io
    nexus_repos_npm_hosted:
      - name: npm-hosted
        blob_store: "{{ nexus_blob_names.npm.blob }}"
    nexus_repos_npm_group:
      - name: npm-group
        blob_store: "{{ nexus_blob_names.npm.blob }}"
        member_repos:
          - npm-hosted
          - npm
    nexus_repos_npm_proxy:
      - name: npm
        blob_store: "{{ nexus_blob_names.npm.blob }}"
        remote_url: https://registry.npmjs.org/
    nexus_repos_apt_proxy:
      - name: deb.debian.org_debian
        remote_url: http://deb.debian.org/debian
        distribution: bullseye
        flat: false
      - name: security.debian.org_debian-security
        remote_url: http://security.debian.org/debian-security
        distribution: bullseye
        flat: false
    nexus_repos_helm_hosted:
      - name: helm-hosted
    nexus_repos_helm_proxy:
      - name: oxyno-zeta.github.io_helm-charts-v2
        remote_url: https://oxyno-zeta.github.io/helm-charts-v2/
      - name: dapr.github.io_helm-charts
        remote_url: https://dapr.github.io/helm-charts/
      - name: charts.bitnami.com_bitnami
        remote_url: https://charts.bitnami.com/bitnami
      - name: aws.github.io_eks-charts
        remote_url: https://aws.github.io/eks-charts
      - name: charts.crossplane.io_stable
        remote_url: https://charts.crossplane.io/stable
      - name: argoproj.github.io_argo-helm
        remote_url: https://argoproj.github.io/argo-helm/
      - name: bitnami-labs.github.io_sealed-secrets
        remote_url: https://bitnami-labs.github.io/sealed-secrets
      - name: https://jaegertracing.github.io/helm-charts
        remote_url: https://jaegertracing.github.io/helm-charts
    nexus_repos_conda_proxy:
      - name: anaconda
        remote_url: 'https://conda.anaconda.org/anaconda/'
      - name: conda-forge
        remote_url: 'https://conda.anaconda.org/conda-forge/'

  roles:
    - ansible-thoteam.nexus3-oss